### ISSUE TITLE
Great job! :)

### ISSUE THREAD

**Issue by jfberhane** [Bucknell-Biol364/Biology205tutorial#14]
https://github.com/Bucknell-Biol364/Biology205tutorial/blob/4148fe6c19e0171ca776abb4bc269973ea3d5b68/Rscript%20document.R#L10

@jssimpson20 Overall I think this was a really good tutorial. I like how clean and easy it is to use. I also like how you cut up the commented areas so that all of the text appears on the screen as a multi line comment with a # on each line. I'll have to change this with my tutorial. I have really long comment lines where the text runs off the screen. Not the easiest to read. I'll acknowledge your group in my tutorial for the idea!

Also, sorry I haven't been referencing the rest of your group! So all of these issues are being sent to you. I only knew you were in this group because you were the one that @ me. But now I realize I probably could have figured out who else is in your group using that html tutorial from a few weeks ago. My bad :/

**Comment by jssimpson20** [comment]
Thank you ! Also, no worries about @-ing me, it's all good. I'll just tag in Chad with the issues. Thank you for your feedback, Chad and I will definitely go through this today and fix what you brought up. @chadsussman

**Comment by chadsussman** [comment]
@jfberhane thanks for the help. If you want to shorten your comment lines, go to code and then "reflow comment" and it will shorten the selected lines
