### ISSUE TITLE
Said this twice

### ISSUE THREAD

**Issue by jfberhane** [Bucknell-Biol364/Biology205tutorial#9]
@jssimpson20 almost the exact same paragraph is above this

**Comment by jssimpson20** [comment]
Hi Julie, maybe I'm not looking properly but what line is the issue on? So I can fix it =)

**Comment by jfberhane** [comment]
@jssimpson20  Here are lines 62-70

#Now we're going to show you how to plot your data, via a scatterplot, to create
#a standard curve. First, you'll have to install ggplot2. When installing
#packages, the package title will be in single quotes, as below. Go ahead and
#run this code:

#Now we're going to show you how to plot your data, via a scatterplot, to create
#a standard curve. First, you'll have to install ggplot2. When installing
#packages, the package title will be in single quotes, as below. Go ahead and
#run this code chunk:
